version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - dojodb
    networks:
      - backend-network
    volumes:
      - .:/app

  dojodb:
    container_name: dojodb
    image: mysql:8.0
    ports:
      - "3535:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
      - ./initDb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network

volumes:
  db-data:

networks:
  backend-network:
    driver: bridge
