-- Aquí va el SQL de la seed
-- Insertar valores en la tabla skill
INSERT INTO skill (name) VALUES 
('JavaScript'),
('TypeScript'),
('Python'),
('Java'),
('C#'),
('C++'),
('Ruby'),
('PHP'),
('Swift'),
('Kotlin'),
('Go'),
('Rust'),
('SQL'),
('NoSQL'),
('HTML'),
('CSS'),
('React'),
('Angular'),
('Vue.js'),
('Node.js'),
('Express.js'),
('Django'),
('Flask'),
('Spring Boot'),
('Laravel'),
('Symfony'),
('ASP.NET'),
('Ruby on Rails'),
('Machine Learning'),
('Data Science'),
('Artificial Intelligence'),
('DevOps'),
('AWS'),
('Azure'),
('Google Cloud'),
('Docker'),
('Kubernetes'),
('Terraform'),
('Ansible'),
('Jenkins'),
('Git'),
('Agile'),
('Scrum'),
('Testing'),
('Unit Testing'),
('Integration Testing'),
('End-to-End Testing'),
('Security'),
('Blockchain'),
('Mobile Development'),
('iOS Development'),
('Android Development'),
('Responsive Design'),
('UI/UX Design'),
('GraphQL'),
('RESTful APIs'),
('Microservices'),
('Serverless Architecture');